version: "3"
networks:
  micro-net:
    driver: bridge
volumes:
  api-gateway-node-modules:
  flights-booking-service-node-modules:
  flights-service-node-modules:
services:
  api_gateway:
    build: ./API-Gateway
    networks:
      - micro-net
    ports: 
      - "5000:5000"
    volumes:
      - ./API-Gateway:/developer/nodejs/api-gateway
      - api-gateway-node-modules:/developer/nodejs/api-gateway/node_modules
  flights_service:
    build: ./Flights-service
    networks:
      - micro-net
    ports: 
      - "3000:3000"
    volumes:
      - ./Flights-service:/developer/nodejs/flights-service
      - flights-service-node-modules:/developer/nodejs/flights-service/node_modules
  flights_booking_service:
    build: ./Flights-Booking-service
    networks:
      - micro-net
    ports: 
      - "4000:4000"
    volumes:
      - flights-booking-service-node-modules:/developer/nodejs/flights-booking-service/node_modules
      - ./Flights-Booking-service:/developer/nodejs/flights-booking-service
